import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    private ItemRepository itemRepository;
    private SalesPromotionRepository salesPromotionRepository;

    public App(ItemRepository itemRepository, SalesPromotionRepository salesPromotionRepository) {
        this.itemRepository = itemRepository;
        this.salesPromotionRepository = salesPromotionRepository;
    }

    public String bestCharge(List<String> inputs) {
        //TODO: write code here
        StringBuilder stringBuilder = new StringBuilder();
        stringBuilder.append("============= Order details =============\n");
        //输入菜品的名字,返回价格和选择的策略
        List<Item> itemList = itemRepository.findAll();
        for (String input : inputs) {
            String[] inputSplit = input.split("x");
            if(inputSplit.length<2)
                return "wrongly input";
            String itemId = inputSplit[0].trim();
            Integer amount=Integer.parseInt(inputSplit[1].trim());
            Optional<Item> itemOptional = itemList.stream().filter(item -> item.getId().equals(itemId)).findFirst();
            itemOptional.ifPresent(
            item -> stringBuilder.append(input)
                    .append(" = ")
                    .append(((int) (item.getPrice()*amount)))
                    .append(" yuan\n")
           );
        }
        //对菜品,计算总价,超过30则减6元
        //同时计算采取优惠策略减少的钱数

       /* stringBuilder
                .append("Braised chicken x 1 = 18 yuan\n")
                .append("Chinese hamburger x 2 = 12 yuan\n")
                .append("Cold noodles x 1 = 8 yuan\n")
                .append("-----------------------------------\n")
                .append("Promotion used:\n")
                .append("Half price for certain dishes (Braised chicken，Cold noodles)，saving 13 yuan\n")
                .append("-----------------------------------\n")
                .append("Total：25 yuan\n")
                .append("===================================");*/

        return stringBuilder.toString();
    }
}
